version: "3.9"
services: 
  server:
    build: ./server
    image: sigmamealcontainer.azurecr.io/server
    container_name: server
    ports: 
      - "80:5000"
    environment: 
      FLASK_ENV: development
  web:
    build: ./client
    image: sigmamealcontainer.azurecr.io/web
    container_name: web
    ports: 
      - "8080:3000"
    depends_on: 
      - server